title: nick haley  •  director
purpose: []
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
color:
  saturation: 1
  brandStrength: 0
  rhythmicContrast: 1
  brandColors:
    - '#FD7630'
    - '#21201D'
    - '#7F402F'
    - '#FFA488'
    - '#A3A2AC'
  lightness: 1
cta:
  bucket: null
  version: null
  domain: null
analytics:
  twitter: null
  google: null
  facebook: null
name: nickhaley
favicon: null
opengraph:
  image: null
  type: null
  appId: null
typography_spectrum: 0.27196
layout_spectrum: 0
